# Generated by Django 2.0.8 on 2019-05-02 17:07

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Caution')),
                ('apl', models.DateField(blank=True, null=True, verbose_name='APL')),
                ('payment', models.CharField(blank=True, choices=[('direct_debit', 'Prélèvement'), ('bank_transfer', 'Virement'), ('check', 'Chèque'), ('cash', 'Espèces'), ('special', 'Special')], max_length=255, verbose_name='Paiement')),
                ('rib', models.BooleanField(default=False, verbose_name='RIB')),
                ('insuranceDeadline', models.DateField(blank=True, null=True, verbose_name="Date de fin d'assurance")),
                ('contractSigned', models.BooleanField(default=False, verbose_name='Contrat signé')),
                ('contractDate', models.DateField(blank=True, null=True, verbose_name='Date du contrat')),
                ('cautionRib', models.BooleanField(default=False, verbose_name='RIB caution')),
                ('idgarant', models.BooleanField(default=False, verbose_name="Pièce d'identité du garant")),
                ('payinslip', models.BooleanField(default=False, verbose_name='3 dernier bulletins de salaire du garant')),
                ('tax_notice', models.BooleanField(default=False, verbose_name="Avis d'imposition du garant")),
                ('stranger', models.BooleanField(default=False, verbose_name='Locataire étranger')),
                ('caf', models.CharField(blank=True, max_length=255, verbose_name='CAF')),
                ('residence_certificate', models.BooleanField(default=False, verbose_name='Certificat de domicile')),
                ('check_guarantee', models.BooleanField(default=False, verbose_name='Chèque pour le complément de dépot de garantie')),
                ('guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Garantie')),
                ('issue', models.BooleanField(default=False, verbose_name='Problème')),
                ('missing_documents', models.TextField(blank=True, verbose_name='Documents manquants')),
                ('date_of_entry', models.DateField(blank=True, null=True, verbose_name="Date d'entrée")),
                ('date_of_departure', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('map', models.ImageField(upload_to='', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom ou niveau')),
                ('description', models.TextField()),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Couleur :')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255, verbose_name='Genre')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Loyer')),
                ('service', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Forfait services')),
                ('charges', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Charges')),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frais de dossier')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Superficie')),
            ],
            options={
                'verbose_name': 'Loyer',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.PositiveIntegerField(verbose_name='Lot')),
                ('room', models.CharField(max_length=6, verbose_name='Chambre')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('map', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Plan')),
                ('current_leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_rooms', to='gestion.Leasing', verbose_name='Dossier actuel')),
                ('next_leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_rooms', to='gestion.Leasing', verbose_name='Dossier suivant')),
                ('renovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.Renovation', verbose_name='Niveau de rénovation')),
                ('rentType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Rent', verbose_name='Loyer')),
            ],
            options={
                'verbose_name': 'Chambre',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'école")),
            ],
            options={
                'verbose_name': 'Ecole',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('school_year', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name="Année d'étude")),
                ('date_of_entry', models.DateField(blank=True, null=True, verbose_name="Date d'entrée à la rez")),
                ('date_of_departure', models.DateField(blank=True, null=True, verbose_name='Date de sortie de la rez')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('temporary', models.BooleanField(default=False, verbose_name='Passager')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Numéro de téléphone portable')),
                ('leaving', models.BooleanField(default=False, verbose_name='Sur le départ')),
                ('waterproof_undersheet', models.BooleanField(default=False, verbose_name='Alèse')),
                ('pillow', models.BooleanField(default=False, verbose_name='Oreiller')),
                ('pillowcase', models.BooleanField(default=False, verbose_name="Taie d'oreiller")),
                ('blanket', models.BooleanField(default=False, verbose_name='Couverture')),
                ('sheet', models.BooleanField(default=False, verbose_name='Drap')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birthcity', models.CharField(blank=True, max_length=255, verbose_name='Ville de naissance')),
                ('birthdepartement', models.CharField(blank=True, max_length=255, verbose_name='Département de naissance')),
                ('birthcountry', models.CharField(blank=True, max_length=255, verbose_name='Pays de naissance')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='N° de rue')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rue')),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Pays')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Téléphone fixe')),
                ('current_leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_tenants', to='gestion.Leasing', verbose_name='Dossier actuel')),
                ('next_leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_tenants', to='gestion.Leasing', verbose_name='Dossier suivant')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.School', verbose_name='Ecole')),
            ],
            options={
                'verbose_name': 'Locataire',
            },
        ),
        migrations.AddField(
            model_name='leasing',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='leasing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Tenant', verbose_name='Locataire'),
        ),
    ]
