# Generated by Django 2.2.1 on 2019-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasing',
            old_name='cautionRib',
            new_name='caution_rib',
        ),
        migrations.RenameField(
            model_name='leasing',
            old_name='contractDate',
            new_name='contract_date',
        ),
        migrations.RenameField(
            model_name='leasing',
            old_name='contractSigned',
            new_name='contract_signed',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='rentType',
            new_name='rent_type',
        ),
        migrations.AlterField(
            model_name='renovation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du niveau'),
        ),
    ]
