# Generated by Django 2.0.8 on 2019-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='supplements',
        ),
        migrations.AddField(
            model_name='rent',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Forfait services'),
            preserve_default=False,
        ),
    ]
