# Generated by Django 2.0.5 on 2018-06-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField(verbose_name="Date d'entrée")),
                ('date_of_departure', models.DateField(verbose_name='Date de sortie')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Caution')),
                ('apl', models.DateField(verbose_name='APL')),
                ('payment', models.CharField(max_length=255, verbose_name='Paiement')),
                ('rib', models.BooleanField(default=False, verbose_name='RIB')),
                ('guaranteeDeadline', models.DateField(verbose_name='Date de fin de garantie')),
                ('contractSigned', models.BooleanField(default=False, verbose_name='Contrat signé')),
                ('contractDate', models.BooleanField(default=False, verbose_name='Date du contrat')),
                ('cautionRib', models.BooleanField(default=False, verbose_name='RIB caution')),
                ('idgarant', models.BooleanField(default=False, verbose_name='Garant')),
                ('payinslip', models.BooleanField(default=False, verbose_name='Bulletin de salaire')),
                ('tax_notice', models.BooleanField(default=False, verbose_name="Avis d'imposition")),
                ('stranger', models.BooleanField(default=False, verbose_name='Etranger')),
                ('caf', models.CharField(max_length=255, verbose_name='CAF')),
                ('residence_certificate', models.BooleanField(default=False, verbose_name='Attestation de résidence')),
                ('check_guarantee', models.BooleanField(default=False, verbose_name='Chèque garantie')),
                ('guarantee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Garantie')),
                ('issue', models.BooleanField(default=False, verbose_name='Problème')),
                ('missing_documents', models.TextField(verbose_name='Documents manquants')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255, verbose_name='Genre')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Loyer')),
                ('rent2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Loyer2')),
                ('supplements', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Suppléments')),
                ('charges', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Charges')),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frais de dossier')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Superficie')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.PositiveIntegerField(verbose_name='Lot')),
                ('building', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('G', 'G')], default='A', max_length=1, verbose_name='Batiment')),
                ('room', models.PositiveIntegerField(verbose_name='Chambre')),
                ('observations', models.TextField(verbose_name='Observations')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('school_year', models.PositiveIntegerField(default=1, verbose_name="Année d'étude")),
                ('date_of_entry', models.DateField(verbose_name="Date d'entrée à la rez")),
                ('date_of_departure', models.DateField(blank=True, verbose_name='Date de sortie de la rez')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('temporary', models.BooleanField(default=False, verbose_name='Passager')),
                ('cellphone', models.TextField(max_length=10, verbose_name='Numéro de téléphone portable')),
                ('leaving', models.BooleanField(default=False, verbose_name='Sur le départ')),
                ('waterproof_undersheet', models.BooleanField(default=False, verbose_name='Alèse')),
                ('pillow', models.BooleanField(default=False, verbose_name='Oreiller')),
                ('pillowcase', models.BooleanField(default=False, verbose_name="Taie d'oreiller")),
                ('blanket', models.BooleanField(default=False, verbose_name='Couverture')),
                ('sheet', models.BooleanField(default=False, verbose_name='Drap')),
                ('birthday', models.DateField(verbose_name='Date de naissance')),
                ('birthcity', models.CharField(max_length=255, verbose_name='Ville de naissance')),
                ('birthdepartement', models.CharField(max_length=255, verbose_name='Département de naissance')),
                ('birthcountry', models.CharField(max_length=255, verbose_name='Pays de naissance')),
                ('street_number', models.PositiveIntegerField(verbose_name='N° de rue')),
                ('street', models.CharField(max_length=255, verbose_name='Rue')),
                ('zipcode', models.PositiveIntegerField(verbose_name='Code postal')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('country', models.CharField(max_length=255, verbose_name='Pays')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.TextField(max_length=10, verbose_name='Téléphone fixe')),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'école"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.School', verbose_name='Ecole'),
        ),
        migrations.AddField(
            model_name='room',
            name='actualTenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='gestion.Tenant', verbose_name='Locataire actuel'),
        ),
        migrations.AddField(
            model_name='room',
            name='nextTenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nextRoom', to='gestion.Tenant', verbose_name='Prochaine locataire'),
        ),
        migrations.AddField(
            model_name='room',
            name='renovation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Renovation', verbose_name='Niveau de rénovation'),
        ),
        migrations.AddField(
            model_name='room',
            name='rentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Rent', verbose_name='Loyer'),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Tenant', verbose_name='Locataire'),
        ),
        migrations.AddField(
            model_name='history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='history',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Tenant', verbose_name='Locataire'),
        ),
    ]
