# Generated by Django 2.2.1 on 2019-07-02 20:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='cellphone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Numéro de téléphone portable'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
    ]
