# Generated by Django 2.2.1 on 2019-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20190522_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Chambre active ?'),
        ),
    ]
