# Generated by Django 2.0.5 on 2018-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20180617_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Locataire'},
        ),
        migrations.AlterField(
            model_name='record',
            name='payment',
            field=models.CharField(choices=[('direct_debit', 'Prélèvement'), ('bank_transfer', 'Virement'), ('check', 'Chèque'), ('cash', 'Espèces'), ('special', 'Special')], max_length=255, verbose_name='Paiement'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='birthcity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ville de naissance'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='birthcountry',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pays de naissance'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='birthdepartement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Département de naissance'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cellphone',
            field=models.TextField(blank=True, max_length=10, verbose_name='Numéro de téléphone portable'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_of_departure',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie de la rez'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée à la rez"),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.TextField(blank=True, max_length=10, verbose_name='Téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='school_year',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name="Année d'étude"),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° de rue'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code postal'),
        ),
    ]
