# Generated by Django 2.0.5 on 2018-07-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20180706_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Loyer'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Chambre'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Ecole'},
        ),
        migrations.AlterField(
            model_name='room',
            name='actualTenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='gestion.Tenant', verbose_name='Locataire actuel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='room',
            name='renovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.Renovation', verbose_name='Niveau de rénovation'),
        ),
    ]
