# Generated by Django 2.2.1 on 2019-05-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_room_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.School', verbose_name='Ecole'),
        ),
    ]
