# Generated by Django 2.2.1 on 2019-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20190529_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° de rue'),
        ),
    ]
