# Generated by Django 2.0.5 on 2018-07-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180706_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro de téléphone portable'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Téléphone fixe'),
        ),
    ]
