# Generated by Django 2.0.5 on 2018-07-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20180707_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='actualTenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='gestion.Tenant', verbose_name='Locataire actuel'),
        ),
    ]
