# Generated by Django 2.0.5 on 2018-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20180707_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historique'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=6, verbose_name='Chambre'),
        ),
    ]
