# Generated by Django 2.0.5 on 2018-07-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20180707_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='nextTenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nextRoom', to='gestion.Tenant', verbose_name='Prochain locataire'),
        ),
    ]
