# Generated by Django 2.0.5 on 2018-07-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20180707_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Caution')),
                ('apl', models.DateField(blank=True, null=True, verbose_name='APL')),
                ('payment', models.CharField(blank=True, choices=[('direct_debit', 'Prélèvement'), ('bank_transfer', 'Virement'), ('check', 'Chèque'), ('cash', 'Espèces'), ('special', 'Special')], max_length=255, verbose_name='Paiement')),
                ('rib', models.BooleanField(default=False, verbose_name='RIB')),
                ('guaranteeDeadline', models.DateField(blank=True, null=True, verbose_name='Date de fin de garantie')),
                ('contractSigned', models.BooleanField(default=False, verbose_name='Contrat signé')),
                ('contractDate', models.BooleanField(default=False, verbose_name='Date du contrat')),
                ('cautionRib', models.BooleanField(default=False, verbose_name='RIB caution')),
                ('idgarant', models.BooleanField(default=False, verbose_name='Garant')),
                ('payinslip', models.BooleanField(default=False, verbose_name='Bulletin de salaire')),
                ('tax_notice', models.BooleanField(default=False, verbose_name="Avis d'imposition")),
                ('stranger', models.BooleanField(default=False, verbose_name='Etranger')),
                ('caf', models.CharField(blank=True, max_length=255, verbose_name='CAF')),
                ('residence_certificate', models.BooleanField(default=False, verbose_name='Attestation de résidence')),
                ('check_guarantee', models.BooleanField(default=False, verbose_name='Chèque garantie')),
                ('guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Garantie')),
                ('issue', models.BooleanField(default=False, verbose_name='Problème')),
                ('missing_documents', models.TextField(blank=True, verbose_name='Documents manquants')),
                ('date_of_entry', models.DateField(blank=True, null=True, verbose_name="Date d'entrée")),
                ('date_of_departure', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Room', verbose_name='Chambre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Historique',
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='room',
        ),
        migrations.RemoveField(
            model_name='history',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
