# Generated by Django 2.0.5 on 2018-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20180710_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasing',
            options={'verbose_name': 'Location'},
        ),
        migrations.AlterField(
            model_name='leasing',
            name='bail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Caution'),
        ),
    ]
