# Generated by Django 2.0.5 on 2018-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20180714_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='contractDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date du contrat'),
        ),
    ]
