# Generated by Django 2.0.5 on 2018-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20180715_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasing',
            name='guaranteeDeadline',
        ),
        migrations.AddField(
            model_name='leasing',
            name='insuranceDeadline',
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin d'assurance"),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='check_guarantee',
            field=models.BooleanField(default=False, verbose_name='Chèque pour le complément de dépot de garantie'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='idgarant',
            field=models.BooleanField(default=False, verbose_name="Pièce d'identité du garant"),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='payinslip',
            field=models.BooleanField(default=False, verbose_name='3 dernier bulletins de salaire du garant'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='residence_certificate',
            field=models.BooleanField(default=False, verbose_name='Certificat de domicile'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='stranger',
            field=models.BooleanField(default=False, verbose_name='Locataire étranger'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='tax_notice',
            field=models.BooleanField(default=False, verbose_name="Avis d'imposition du garant"),
        ),
    ]
