# Generated by Django 2.0.5 on 2018-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.ImageField(upload_to='', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
