# Generated by Django 2.0.8 on 2019-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeText', models.TextField(blank=True, help_text="Ce texte sera affiché sur la page d'accueil, avant les documents", verbose_name="Texte d'accueil")),
                ('english_homeText', models.TextField(blank=True, verbose_name="Texte d'accueil (anglais)")),
            ],
        ),
    ]
