# Generated by Django 2.1 on 2019-05-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aloes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpreferences',
            old_name='english_homeText',
            new_name='english_home_text',
        ),
        migrations.RenameField(
            model_name='generalpreferences',
            old_name='homeText',
            new_name='home_text',
        ),
    ]
