# Generated by Django 2.0.5 on 2018-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpreferences',
            name='homeText',
            field=models.TextField(blank=True, help_text="Ce texte sera affiché sur la page d'accueil, avant les documents", verbose_name="Text d'accueil"),
        ),
    ]
