# Generated by Django 2.0.5 on 2018-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloes', '0002_auto_20180615_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='english_homeText',
            field=models.TextField(blank=True, verbose_name="Texte d'accueil (anglais)"),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='homeText',
            field=models.TextField(blank=True, help_text="Ce texte sera affiché sur la page d'accueil, avant les documents", verbose_name="Texte d'accueil"),
        ),
    ]
