# Generated by Django 2.0.5 on 2018-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='english_description',
            field=models.TextField(blank=True, verbose_name='Description (anglais)'),
        ),
        migrations.AddField(
            model_name='document',
            name='english_document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fichier (anglais)'),
        ),
        migrations.AddField(
            model_name='document',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du document (anglais)'),
        ),
    ]
